# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: CJM Films
email: christopherjohn27@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Chris Malanchen is a professional film and television editor based in Toronto, Canada. His background is in the fine arts: drawing and painting. He explored a passion for filmmaking while attending art school and discovered his favorite role was editing.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://cjmfilms.netlify.app" # the base hostname & protocol for your site
twitter_username: 
github_username: danielcarlyle 

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed

sass:
  style: compressed
  sass_dir: _sass  

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
