tel: "15142939962"
tel_display: "514 293 9962"

seo:
  tagline: "StillWaves is a Toronto based post-punk band featuring Daniel Carlyle."
        
location:
  description: "StillWaves is a Toronto based post-punk band featuring Daniel Carlyle"
  city: "Toronto"
  region: "Ontario"
  country: "Canada"
  
front_page_video: '<div style="padding:55.25% 0 0 0;position:relative;"><iframe src="https://player.vimeo.com/video/346738342?title=0&byline=0&portrait=0" style="position:absolute;top:0;left:0;width:100%;height:100%;" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe></div><script src="https://player.vimeo.com/api/player.js"></script>'


bio_description: "<p>StillWaves formed from a mutual love and admiration of post-punk heavyweights like Killing Joke, The Sound and The Chameleons. Daniel Carlyle and Eric Pentz had met various hazy nights in Toronto, and eventually came together and began writing and crafting their sound.

After several months of writing and rehearsing, they took a chance, sending some poorly recorded demos to local producer/musician and recording guru Josh Korody, and he liked it enough to record their first album. Recorded and Produced by Korody and mastered by Jesse Keeler (Death from Above/Mstrkrft), The album tentatively titled, 'Regressing Times,' also features drums by Mike Wallace (Preoccupations).

Carlyle's vocals and the themes of the songs focus on topics like the (often) sombre state of the world, past scorned love, and the inherent inequalities of the world. Dark music, for dark times indeed. Restless souls make restless music.

Daniel Carlyle – Vocals, Bass, Keyboards, Sampler/Programming

Eric Pentz – Guitar, Keyboards </p>"

bio_accomplishments: "
                <li>2019, Measure, (TIFF) Toronto International Film Festival, Nominee best Canadian Short Film</li>
                <li>2019, Jury, (CCE) Canadian Cinema Editors awards</li>
                <li>2018, Records People Music (Director), Official Selection Edmonton International Film Festival</li>
                <li>2018, Canadian Film Centre, Editors Lab Resident</li>
                <li>2016, The Weekend Sailor, AMACC, Mexican Academy of Motion Picture Arts and Sciences, Nominee best Documentary</li>
                <li>2016, The Weekend Sailor, Doc La, WINNER best Screenwriter</li> 
                <li>2016, The Weekend Sailor, American Film Award, Nominee, Best Feature Film</li>
                <li>2016, The Weekend Sailor, International Filmmaker Festival of World Cinema Nice, Nominee Nest Editing of a Feature Film, Best Feature Documentary</li>
                <li>2016, The Weekend Sailor, Peurto Vallarta International Film Festival, Winner Best Film</li>
                <li>2016, The Weekend Sailor, Tbilisi Sports Film Festival, Nominee Best Editing</li>
                <li>2016, The Weekend Sailor, Waimea Ocean Film Festival, Winner Best Film & Edge of Seat Award</li>                
                <li>2011, The Imagined States of America, (FIFA Montreal) Montréal International Festival of Films on Art</li> 
                <li>2010, The Remones (Director), Official Selection Edmonton International Film Festival</li>
                <li>2010, The Remones (Director), Official Selection Calgary Underground Film Festival</li>
                <li>2006, Colouring Outside The Lines (Director), Calgary Children's Fringe Film Festival</li>"

