tel: "15142939962"
tel_display: "514 293 9962"

seo:
  tagline: "Christopher Malanchen is an Editor for Film and Televison, based in
    Toronto, Ontario, Canada."
        
location:
  description: "Based in"
  city: "Toronto"
  region: "Ontario"
  country: "Canada"
  
front_page_video: '<div style="padding:55.25% 0 0 0;position:relative;"><iframe src="https://player.vimeo.com/video/346738342?title=0&byline=0&portrait=0" style="position:absolute;top:0;left:0;width:100%;height:100%;" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe></div><script src="https://player.vimeo.com/api/player.js"></script>'


bio_description: "<p>I am a professional film and television editor based in
  Toronto, Canada. My background is in the fine arts: drawing and painting. I
  explored my passion for filmmaking while attending art school and discovered
  my favorite role was editing. </p><p>As a resident editor at the Canadian Film
  Centre, I had the opportunity to further develop my storytelling skills and
  concentrate on scripted narrative filmmaking. I collaborated with talented
  directors from across Canada making high caliber films, representing diverse
  experiences and voices.</p><p>As a freelance editor I work in several genres,
  including documentaries, short films, comedy, scripted narrative television
  and factual television. I gained important edit room experience working on
  premium projects, including Big Little Lies (Season 2), The Art of More,
  Pillars of the Earth and The Weekend Sailor.</p><p>My editing work has been
  screened at numerous film festivals internationally such as TIFF, FIFA
  Montreal, DOC LA and Madrid International Film Festival and is broadcast on
  the Discovery Channel, Cooking Channel, History Channel, Netflix, SyFy, CBC,
  Vice and Sony Entertainment. </p>"

bio_accomplishments: "
                <li>2019, Measure, (TIFF) Toronto International Film Festival, Nominee best Canadian Short Film</li>
                <li>2019, Jury, (CCE) Canadian Cinema Editors awards</li>
                <li>2018, Records People Music (Director), Official Selection Edmonton International Film Festival</li>
                <li>2018, Canadian Film Centre, Editors Lab Resident</li>
                <li>2016, The Weekend Sailor, AMACC, Mexican Academy of Motion Picture Arts and Sciences, Nominee best Documentary</li>
                <li>2016, The Weekend Sailor, Doc La, WINNER best Screenwriter</li> 
                <li>2016, The Weekend Sailor, American Film Award, Nominee, Best Feature Film</li>
                <li>2016, The Weekend Sailor, International Filmmaker Festival of World Cinema Nice, Nominee Nest Editing of a Feature Film, Best Feature Documentary</li>
                <li>2016, The Weekend Sailor, Peurto Vallarta International Film Festival, Winner Best Film</li>
                <li>2016, The Weekend Sailor, Tbilisi Sports Film Festival, Nominee Best Editing</li>
                <li>2016, The Weekend Sailor, Waimea Ocean Film Festival, Winner Best Film & Edge of Seat Award</li>                
                <li>2011, The Imagined States of America, (FIFA Montreal) Montréal International Festival of Films on Art</li> 
                <li>2010, The Remones (Director), Official Selection Edmonton International Film Festival</li>
                <li>2010, The Remones (Director), Official Selection Calgary Underground Film Festival</li>
                <li>2006, Colouring Outside The Lines (Director), Calgary Children's Fringe Film Festival</li>"

